#cloud-config

package_update: true
package_upgrade: true

system_info:
    default_user:
        name: lmurarotto
        lock_passwd: false
        sudo: ["ALL=(ALL) ALL"]

preserve_hostname: false
manage_etc_hosts: true
fqdn: code.murar8.link
