#cloud-config

package_update: true
package_upgrade: true

system_info:
    default_user:
        name: "$USER"
        ssh_authorized_keys: { "$PUBLIC_KEY" }

preserve_hostname: false
manage_etc_hosts: true
fqdn: "$FQDN"
