name: Deploy

on: { push: { branches: [main] } }

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"

            - run: npm install

            - run: npm run lint:prettier

            - run: npm run lint:eslint

            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-region: ${{ secrets.AWS_REGION }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - run: scripts/create-image.sh

            - uses: pulumi/actions@v3
              with:
                  command: up
                  stack-name: main
              env: { PULUMI_ACCESS_TOKEN: "${{ secrets.PULUMI_ACCESS_TOKEN }}" }

            - run: scripts/destroy-image.sh
