name: Deploy

on: { push: { branches: [main] } }

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"

            - run: npm install

            - run: npm run lint:prettier

            - run: npm run lint:eslint

            - uses: pulumi/actions@v3
              with:
                  command: up
                  stack-name: main
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
                  # TODO aws credentials
